SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_INVUNERBILITY = 0.25
BOSS_HEALTH = 10

PLAYER_RADIUS = 20

PLAYER_TURN_SPEED = 300

PLAYER_SPEED = 200

PLAYER_SHOOT_SPEED = 500

PLAYER_SHOOT_COOLDOWN = 0.5

UPGRADE_TURN_SPEED = 100

SHOT_RADIUS = 5

SHOT_DAMAGE = 5

UPGRADE_RADIUS = 15
UPGRADE_COLOUR = ["yellow", "red", "blue", "green"]
# movement speed, shot speed, bullet size, bullet pierce

UPGRADE_DESPAWN = 10
UPGRADE_COOLDOWN = 10
